app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    pass_secure = db.Column(db.String(255))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())

    blogs = db.relationship('Blog', backref='blogyou',lazy=True)
    comment = db.relationship('Comments', backref='commenting',lazy=True)


    @property
    def password(self):
            raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
            self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
            return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f'User {self.username}'


class Blog(db.Model):
    id = db.Column(db.Integer,primary_key=True)
    title = db.Column(db.String(100),nullable=False)
    date_posted = db.Column(db.DateTime,nullable=False,default=datetime.utcnow)
    blog = db.Column(db.Text,nullable=False)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'),nullable=False)
    comment_it = db.relationship('Comments', backref='user_comment',lazy=True)

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()


    def __repr__(self):
        return f"Blog('{self.title}', '{self.date_posted}')"




class Comments(db.Model):
    id = db.Column(db.Integer,primary_key=True)
    comment = db.Column(db.String(255),nullable=False)
    date_posted = db.Column(db.DateTime,nullable=False,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    blog_id = db.Column(db.Integer,db.ForeignKey('blog.id'))

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()


    def __repr__(self):
        return f"Comments('{self.comment}', '{self.date_posted}')"

class Subscribe(db.Model):
    id = db.Column(db.Integer,primary_key=True)
    email = db.Column(db.String(100))
    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()
    def __repr__(self):
        return f"Comments('{self.email}')"

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SelectField,TextAreaField,SubmitField
from wtforms.validators import Required


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask_sqlalchemy import SQLAlchemy
from flask import Flask
from flask_mail import Mail
from flask_bootstrap import Bootstrap
from config import config_options
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from werkzeug.utils import secure_filename
from werkzeug.datastructures import FileStorage


login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


boostrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
mail = Mail()

def create_app(config_name):
    #Initializing application
    app = Flask(__name__)
    
    # Create the app configuration
    app.config.from_object(config_options[config_name])

    #Initializing Flask Extensions
    mail.init_app(app)
    boostrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    
    
    # configure UploadSet
    configure_uploads(app,photos)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/auth')

    return app 

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views,forms

app/main/views.py
from flask import render_template, request, redirect, url_for, abort
from . import main
from ..models import User, Blog, Subscribe, Comments
from .forms import UpdateProfile
from .. import db,photos
from flask_login import login_user, login_required, logout_user, current_user
from ..email import mail_message
from flask_mail import Message
from .. import mail
from ..requests import get_quotes

# Views
@main.route('/')
def index():

    '''
    View root page function that returns the index page and its data
    '''
    title = 'Home - Think|Space'
    # Getting the quotes
    quotes = get_quotes()
    print(quotes)
    return render_template('index.html',title=title,quotes=quotes)
    

@main.route('/home')
@login_required
def home():

    title = 'Home - Think|Space'
    blogs = Blog.query.all()
    comment = Comments.query.all()
    
    return render_template('home.html', title=title,blogs=blogs,comment=comment,)


@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user=user)
    
@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html', form=form)
    
@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile', uname=uname))

@main.route('/blogs', methods=['POST','GET'])
@login_required
def blogs():
    if request.method == 'POST':
        form = request.form
        title = form.get('title')
        blog = form.get('blog')
        if title==None or blog==None:
            error = "All fields are required"
            return render_template('create_blog.html', error=error)
        blog = Blog(title=title,blog=blog, user_id=current_user.id)
        blog.save()
        subscribers = Subscribe.query.all()
        for subscriber in subscribers:
            mail_message("Hello,New Blog has been created", "email/new_blog",subscriber.email,blog=blog)
        return redirect(url_for('main.home'))
    return render_template('create_blog.html')


@main.route('/delete/<int:comment_id>')
@login_required
def delete(comment_id):
    comm = Comments.query.get(comment_id)
    comm.delete()
    return redirect(url_for('main.home'))


@main.route('/del/<int:blog_id>', methods=['POST','GET'])
@login_required
def del_blog(blog_id):
    blog = Blog.query.get(blog_id)
    blog.delete()
    return redirect(url_for('main.home'))


@main.route('/comment/<int:blog_id>', methods=['GET','POST'])
def comment(blog_id):
    if request.method == 'POST':
        comment = request.form.get('comment')
        blog = Blog.query.filter_by(id=blog_id).first()
        comment = Comments(comment=comment,blog_id=blog.id)
        comment.save()
        return redirect(url_for('main.home',blog=blog))
    return render_template('home.html')

@main.route('/subscribe', methods=['GET','POST'])
def subscribe():
    if request.method == "POST":
        form = request.form
        email = form.get("email")
        if email==None:
            error = "Enter your email required"
            return render_template('home.html', error=error)
        user = Subscribe(email=email)
        user.save()
        users = Subscribe.query.all()
        for user in users:
            mail_message("Hello", "email/subscribe",user.email,user=user)
        return redirect(url_for("main.home"))
    return render_template('home.html')

app/templates/base.html
{% extends 'bootstrap/base.html'%}
{% block styles %}
{{ super()}}
<!-- styles links -->

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css" />
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}" />

{% endblock %}

<!-- Navbar block  -->
{% block navbar %}
{% include 'navbar.html' %}
{% endblock %}

app/templates/create_blog.html
{% extends 'base.html' %}

{% block content %}
{{super()}}
<div class="container">
    <div class="row">
        <div class="blog">
            <div class="card">
                <form action="/blogs" method="POST">
                    <div class="card-header">
                        {% if error %}
                        <p class="alert-alert-danger text-center mt-2 bg-danger">
                            {{error}}
                        </p>
                        {% endif %}
                    </div>
                    <div class="card-body">
                        <div class="text-center">
                            <p>Create a blog</p>
                            <hr>
                            <input size="100%" type="text" placeholder="Title" name="title" required>
                            <br>
                            <br>
                            <textarea type="text" name="blog" rows="5" cols="100" placeholder="Write a blog"
                                required></textarea>
                            <br>
                            <input type="submit" value="Submit" class="btn bg-danger text-uppercase">
                        </div>

                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home.html
{% include 'base.html'%}
{% block content%}
<div class=" container">
    <div class="">

        <form class="text-center" action="/subscribe" method='POST'>
            <h4>Subscribe</h4>
            <input type="text" name="email" placeholder="Enter email">
            <br>
            <input class="btn btn-primary " type="submit" value="Submit">
        </form>
    </div>
    <div class="row">

        {% for blog in blogs%}
        <div class="row">
            <div class="card bg-light text-center">
                <div class="card-header text-left">
                    <i class="fa fa-user-circle-o" style="font-size:24px"></i> {{blog.blogyou.username}}
                </div>
                <div style="float: right;">{%  if current_user == blog.blogyou %}
                    <a href="{{url_for('main.del_blog',blog_id=blog.id)}}"><i class="fa fa-trash-o"
                            style="font-size:24px;color:red"></i></a>
                    {% endif %}
                </div>
                <div class="card-title  text-uppercase">
                    <h5>{{blog.title}}</h5>
                </div>
                <hr>
                <div class="card-body">

                    <p>{{blog.blog}}</p>
                </div>
                <div class="card-body">
                    <p>{{blog.date_posted.strftime('%Y-%m-%d')}}</p>

                    <div class="card com">

                        <h4 class=""><i class="fa fa-comments-o" style="font-size:24px;"></i> Comments</h4>
                        {% for comm in comment %}
                        {% if blog.id == comm.blog_id %}
                        <div style="float: right;">{%  if current_user == blog.blogyou %}
                            <a href="{{url_for('main.delete',comment_id=comm.id)}}"><i class="fa fa-trash-o"
                                    style="font-size:24px;color:red"></i></a>
                            {% endif %}
                        </div>
                        <div class="divide">
                            <div class="card-body">{{comm.comment}}</div>
                            <p class="blockquote">{{comm.date_posted.strftime('%y-%m-%d')}}</p>
                        </div>
                        <hr>
                        {% endif %}
                        {% endfor %}
                        <form class="" style="justify-content: center;"
                            action="{{url_for('main.comment',blog_id=blog.id)}}" method="post">
                            <input type="text" name="comment" class="" style="width: 100%;">
                            <input type="submit" placeholder="Comment" class="btn btn-success">
                        </form>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

app/templates/index.html
{% include 'base.html' %}
<!-- Styles block -->

{% block styles%}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}

<!--Content block-->
{% block content%}
<div class="containe text-center" style="text-align: center; margin-top: 0px;">
    <div class="pimg1"></div>

    <h1>Welcome to Think | Space</h1>
    <div>
        {% if current_user.is_authenticated%}
        <a id=" start" class="btn btn-danger text-center" href="{{url_for('main.home')}}"><span class="view">View
                Blogs</span></a>
        {% else %}
        <a id="start" class="btn btn-danger text-center" href="{{url_for('auth.login')}}"><span class="view">Sign
                In</span>
        </a>
    </div>
    {% endif %}
</div>
<div class="">
    <h3 class="text-center">
        Quote of the day
    </h3>
    <h4 class="text-center container"><i class="fa fa-quote-left" style="font-size:24px"></i>
        {{quotes.quote}}
        <i class="fa fa-quote-right" style="font-size:24px"></i></h4>
    <p class="text-muted text-center"><em>By: ~{{quotes.author}}~</em></p>
</div>
{% endblock %}

app/templates/navbar.html
<nav class="navbar " style="background-color: #86c232;" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> Think|Space </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="nav-item"><a class="nav-link" href="/"><i class="fa fa-fw fa-home"
                            style="font-size:24px"></i> Home</a></li>
            </ul>
            <ul class="nav navbar-nav">
                <li class="nav-item"><a class="nav-link" href="/home"><i class="fa fa-newspaper-o"
                            style="font-size:24px"></i> Blogs</a></li>
            </ul>
            <ul class="nav navbar-nav">
                <li class="nav-item"><a class="nav-link" href="/blogs"><i class="fa fa-pencil"
                            style="font-size:24px"></i> Create Blog</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}

                <li style="color: white; padding: 15px;">
                    <i class="fa fa-fw fa-user" style="font-size:24px"></i>
                    {{current_user.username}}
                </li>
                <li>
                    <a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a>
                </li>
                <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                {% else %}
                <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                {%endif%}
            </ul>
        </div>
    </div>
</nav>

app/templates/profile/profile.html
{% extends 'base.html'%} {% block content %}
<div class="container">
    <div class="row">
        <!-- displaying  Username-->
        <div class="col-md-4">
            <h3>{{user.username| capitalize}}</h3>

            <!--Displaying user bio-->
            {% if user.bio %}
            <h4 style="color: #233D4D; font-style: italic;">{{user.bio}}</h4>
            {%else%}
            <p>{{user.username| capitalize}} has no bio</p>
            {% endif %}
        </div>

        <!--Display profile photo-->
        <div class="col-md-4">
            {% if user.profile_pic_path %}

            <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail" />

            {%else%}
            <p>No profile picture</p>

            {% endif %}
            {% if user == current_user %}
            <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
            {% endif %}
            {% if user == current_user %}
            <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post"
                enctype="multipart/form-data">
                <input type="file" name="photo" class="form-control" required />
                <input type="submit" />
            </form>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %} {% import 'bootstrap/wtf.html' as wtf %} {% block
content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}